### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by livejamie** [testpushpleaseignore/acquisition#10]
Is this something you're still working on? The original Acquisition isn't working at all right now and needs a simple fix: https://github.com/xyzz/acquisition/issues/576

I would be happy to switch to your fork if you plan on keeping it up

**Comment by testpushpleaseignore** [comment]
I haven't been keeping up on this project much recently, but I could look into fixing this error. Hopefully I can figure out what's going on here!

**Comment by testpushpleaseignore** [comment]
As an update, I'm still getting a 403 error, even when using the https link. Still looking into why I'm getting that error.

**Comment by testpushpleaseignore** [comment]
May have figured out the issue, since it seems that Cloudflare may be blocking the requests from the program, when there weren't a user-agent defined in the http request. Seeing if I can get this fully working here shortly.

**Comment by testpushpleaseignore** [comment]
0.8e released to fix this issue.
