### ISSUE TITLE
Importing prices from xyzz's original acquisition

### ISSUE THREAD

**Issue by aiolos01** [testpushpleaseignore/acquisition#14]
I posted about this in xyzz's #576 issue in which you participated but didn't get a reply so I'm reposting it here.

I'm interested in am acquisition  fork that is actually maintained to avoid issues in the future and get some extra features too. My question is, if I uninstall xyzz's version and install yours do I lose all the prices I have set? Can I backup the database and import it into yours?

**Comment by testpushpleaseignore** [comment]
See my recent release below which should have the database backup working again:
https://github.com/testpushpleaseignore/acquisition/releases/tag/v0.9.1

Also I should add, that the prices stored in `%LOCALAPPDATA%\acquisition\data` should carry over just fine in my fork just fine, but in the event something goes wrong when upgrading to v0.9.1, then you can follow the steps on how to rollback with the above link.

Hopefully this helps!

**Comment by aiolos01** [comment]
Perfect, I'll be sure to try this then. Thank you.
