### ISSUE TITLE
Support for fractured mods

### ISSUE THREAD

**Issue by aiolos01** [testpushpleaseignore/acquisition#17]
Fractured mods are not shown at all on items.

**Comment by testpushpleaseignore** [comment]
Could you provide a screenshot of a mod that's not showing up? And is this a mod that's not showing up in the filter dropdown when pressing "Add mod", or is this a mod that you can see in-game, but not in Acquisition?

**Comment by aiolos01** [comment]
I think it happens with every fractured mod. At least with every one I've tried. Here are several examples.

[url=https://postimg.cc/VdTpSp19][img]https://i.postimg.cc/VdTpSp19/Snap271.png[/img][/url]

[url=https://postimg.cc/bdyK413n][img]https://i.postimg.cc/bdyK413n/Snap272.png[/img][/url]

[url=https://postimg.cc/230PY3KK][img]https://i.postimg.cc/230PY3KK/Snap273.png[/img][/url]

[url=https://postimg.cc/vgzCcmHD][img]https://i.postimg.cc/vgzCcmHD/Snap274.png[/img][/url]

[url=https://postimg.cc/sv1bgsFD][img]https://i.postimg.cc/sv1bgsFD/Snap275.png[/img][/url]

[url=https://postimg.cc/BPnkDGXp][img]https://i.postimg.cc/BPnkDGXp/Snap276.png[/img][/url]

**Comment by testpushpleaseignore** [comment]
Should have this fixed now in [v0.9.3](https://github.com/testpushpleaseignore/acquisition/releases/tag/v0.9.3). Thanks!

**Comment by aiolos01** [comment]
Works great, thanks for the quick fix.

**Comment by aiolos01** [comment]
Hello again,
quick question. Is it normal for the database to be 2,5GB in size? I
checked the previous version backups (had them since 0.5) in
\AppData\Local\acquisition and they were a few MB in size. 0.91 was 200MB
and 0.92 1,7GB. Now the data folder is 2,5GB. In contrast 0.7 for example
was 18MB. I have a lot of items but 2,5GB seems excessive.

Thanks again

**Comment by testpushpleaseignore** [comment]
@aiolos01 
Could you provide some additional info in #18 for me? I think that there might be some old data sticking around in the items table of that database, but can't seem to be able to reproduce the problem myself yet.
