### ISSUE TITLE
Add identifiable User Agent

### ISSUE THREAD

**Issue by Novynn** [testpushpleaseignore/acquisition#21]
This application isn't following GGG's [User Agent](https://www.pathofexile.com/developer/docs#guidelines) rules.

**Comment by testpushpleaseignore** [comment]
Thanks for the info! Yeah I can update that here hopefully today.

**Comment by testpushpleaseignore** [comment]
Sorry for not getting to this sooner, but should have this fixed in my v0.9.6 release.
