### ISSUE TITLE
Again can't login, again API problem

### ISSUE THREAD

**Issue by Einaar** [testpushpleaseignore/acquisition#23]
![Image_1](https://user-images.githubusercontent.com/119501219/204792704-ddfc17ac-3a3f-40c0-9964-da5c29092bc5.jpg)

**Comment by flesyMeM** [comment]
Yep, suddenly started getting the same yesterday morning.

**Comment by aiolos01** [comment]
Yes the same issue again. I waited a day before reporting it as it could get fixed as the previous time but it hasn't. The strange thing is that the URL works fine from a browser.

**Comment by testpushpleaseignore** [comment]
Sorry for not getting to this sooner, but should have this fixed in my v0.9.6 release.
