### ISSUE TITLE
connection timed out error in acquisition

### ISSUE THREAD

**Issue by 85ip9gh** [testpushpleaseignore/acquisition#24]
![acq](https://user-images.githubusercontent.com/119688837/205334056-b2b95b5a-346e-416a-8fbd-b58e588e5d5d.png)

**Comment by testpushpleaseignore** [comment]
What happens if you take any of those URLs from that error, and open them in a web browser? Wasn't sure if those domains were being blocked at all, or if something else is going on.

**Comment by 85ip9gh** [comment]
![image](https://user-images.githubusercontent.com/119688837/205418995-503b2416-f87e-4121-bf48-dbf1413d45cc.png)
![image](https://user-images.githubusercontent.com/119688837/205419018-2fc969f0-3c56-4b1c-ab4b-4fa32046e508.png)
![image](https://user-images.githubusercontent.com/119688837/205419039-1acc805b-1ba3-4443-88ca-23f382e413fd.png)

**Comment by testpushpleaseignore** [comment]
Did it happen to take a long time to load any of those links when in the web browser? Wasn't sure if you were on a slower connection currently.

Can't think of a reason as to why it would work in a browser, but not in the app right now.

**Comment by 85ip9gh** [comment]
No, they were pretty fast to load. Second/third link maybe took like 3sec to load fully, but first one was instant.

**Comment by 85ip9gh** [comment]
Turns out it was something with my modem. Just restarted it, and acquisition is working now, pob can check for updates properly now too Sorry about this.
