### ISSUE TITLE
cant fetch tabs 3.20

### ISSUE THREAD

**Issue by mega2k0** [testpushpleaseignore/acquisition#25]
lot of errors right now, non object response random error transfering and bad requests

also console says shop updated but nothing updated on forum

**Comment by testpushpleaseignore** [comment]
Could you log out of the pathofexile.com website, and then back in? Hopefully that would fix your issue when logging into Acquisition.

Otherwise if that doesn't work, then we could see what else needs to be done.

**Comment by testpushpleaseignore** [comment]
Thanks for the update! Glad to hear that getting a new POESSID fixed your issue.
