### ISSUE TITLE
When scrolling right on the search tabs, it will create a new tab

### ISSUE THREAD

**Issue by testpushpleaseignore** [testpushpleaseignore/acquisition#8]
Have it stop once it reaches the last tab instead of creating a new tab.

**Comment by SkyNet7k** [comment]
How about community this error appears when I try to update the tabs

ERROR 2022-05-06T10:29:19.740 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. If you're using Steam to login make sure you use the same login method (steam or login/password) in Acquisition, Path of Exile website and Path of Exile game client. For example, if you created a shop thread while using Steam to log into the website and then logged into Acquisition with login/password it will not work. In this case you should either recreate your shop thread or use a correct login method in Acquisition.

**Comment by DeksterSteinhart** [comment]
same have this error

**Comment by DeksterSteinhart** [comment]
i fix error, just logged in forum via steam authorization and use this session id. But now when i update shop nothing happening... No errors no updates on forum. Just this message.
 INFO 2022-05-07T10:10:53.719 "Received 8 tabs [0 from cache]"

**Comment by DeksterSteinhart** [comment]
Yes need to check upload scripts i think when you update shop it was marked empty.

**Comment by testpushpleaseignore** [comment]
closing this issue for now since it's off topic, but can review this sort of issue again in the future.
