### ISSUE TITLE
Cannot login to the 0.8.c version

### ISSUE THREAD

**Issue by Arecurius0** [testpushpleaseignore/acquisition#9]
![grafik](https://user-images.githubusercontent.com/36637378/107445362-9a8be000-6b3c-11eb-88ad-ede60416b4f1.png)

logging into the 0.8.b version (with old cached login and only updated poesessid) prior to reinstalling the updated version worked fine

**Comment by eugenikus8** [comment]
I have the same problem.

**Comment by testpushpleaseignore** [comment]
Sorry all for not providing an update sooner, but the 0.8d update should fix this issue.
